import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}

// created by chatgpt
export function formatDateString(dateString: string) {
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "short",
    day: "numeric",
  };

  const date = new Date(dateString);
  const formattedDate = date.toLocaleDateString(undefined, options);

  const time = date.toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });

  return `${time} - ${formattedDate}`;
}

// created by chatgpt
export function formatThreadCount(count: number): string {
  if (count === 0) {
    return "No Threads";
  } else {
    const threadCount = count.toString().padStart(2, "0");
    const threadWord = count === 1 ? "Thread" : "Threads";
    return `${threadCount} ${threadWord}`;
  }
}

export const parseSocialNumbers = (number: number): string => {
  switch (true) {
    case number < 1000:
      return number.toString();
    case number < 1000000:
      const thousands = number / 1000;
      return thousands % 1 === 0
        ? `${thousands}K`
        : `${thousands.toFixed(1).replace(/\.0$/, "")}K`;
    case number < 1000000000:
      const millions = number / 1000000;
      return millions % 1 === 0
        ? `${millions}M`
        : `${millions.toFixed(1).replace(/\.0$/, "")}M`;
  }

  return "";
};
